// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/image_engine.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  RustStreamSink<CompressionTaskProgress>
  dco_decode_StreamSink_compression_task_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CompressionRequest dco_decode_box_autoadd_compression_request(dynamic raw);

  @protected
  CompressionResponse dco_decode_box_autoadd_compression_response(dynamic raw);

  @protected
  CompressionRequest dco_decode_compression_request(dynamic raw);

  @protected
  CompressionResponse dco_decode_compression_response(dynamic raw);

  @protected
  CompressionTaskProgress dco_decode_compression_task_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<CompressionRequest> dco_decode_list_compression_request(dynamic raw);

  @protected
  List<CompressionResponse?>
  dco_decode_list_opt_box_autoadd_compression_response(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CompressionResponse? dco_decode_opt_box_autoadd_compression_response(
    dynamic raw,
  );

  @protected
  OutputFormat dco_decode_output_format(dynamic raw);

  @protected
  ResizeMode dco_decode_resize_mode(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  RustStreamSink<CompressionTaskProgress>
  sse_decode_StreamSink_compression_task_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CompressionRequest sse_decode_box_autoadd_compression_request(
    SseDeserializer deserializer,
  );

  @protected
  CompressionResponse sse_decode_box_autoadd_compression_response(
    SseDeserializer deserializer,
  );

  @protected
  CompressionRequest sse_decode_compression_request(
    SseDeserializer deserializer,
  );

  @protected
  CompressionResponse sse_decode_compression_response(
    SseDeserializer deserializer,
  );

  @protected
  CompressionTaskProgress sse_decode_compression_task_progress(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<CompressionRequest> sse_decode_list_compression_request(
    SseDeserializer deserializer,
  );

  @protected
  List<CompressionResponse?>
  sse_decode_list_opt_box_autoadd_compression_response(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CompressionResponse? sse_decode_opt_box_autoadd_compression_response(
    SseDeserializer deserializer,
  );

  @protected
  OutputFormat sse_decode_output_format(SseDeserializer deserializer);

  @protected
  ResizeMode sse_decode_resize_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_compression_task_progress_Sse(
    RustStreamSink<CompressionTaskProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compression_request(
    CompressionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_compression_response(
    CompressionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_request(
    CompressionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_response(
    CompressionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_task_progress(
    CompressionTaskProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_compression_request(
    List<CompressionRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_compression_response(
    List<CompressionResponse?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_compression_response(
    CompressionResponse? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_format(OutputFormat self, SseSerializer serializer);

  @protected
  void sse_encode_resize_mode(ResizeMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
