// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/history/data/models/compression_history_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3600473206471130881),
    name: 'CompressionHistoryModel',
    lastPropertyId: const obx_int.IdUid(8, 1422837674477831830),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6015656902727101552),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1804399586164108935),
        name: 'originalPath',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 8909184179453716877),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3059497527113220085),
        name: 'outputPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 639845181412522347),
        name: 'outputFileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8857507443483171961),
        name: 'originalBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2570105691793257623),
        name: 'compressedBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6360721508005066328),
        name: 'timestamp',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(2, 4139996538920791190),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1422837674477831830),
        name: 'format',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3600473206471130881),
    lastIndexId: const obx_int.IdUid(2, 4139996538920791190),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CompressionHistoryModel: obx_int.EntityDefinition<CompressionHistoryModel>(
      model: _entities[0],
      toOneRelations: (CompressionHistoryModel object) => [],
      toManyRelations: (CompressionHistoryModel object) => {},
      getId: (CompressionHistoryModel object) => object.id,
      setId: (CompressionHistoryModel object, int id) {
        object.id = id;
      },
      objectToFB: (CompressionHistoryModel object, fb.Builder fbb) {
        final originalPathOffset = fbb.writeString(object.originalPath);
        final outputPathOffset = fbb.writeString(object.outputPath);
        final outputFileNameOffset = fbb.writeString(object.outputFileName);
        final formatOffset = fbb.writeString(object.format);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, originalPathOffset);
        fbb.addOffset(2, outputPathOffset);
        fbb.addOffset(3, outputFileNameOffset);
        fbb.addInt64(4, object.originalBytes);
        fbb.addInt64(5, object.compressedBytes);
        fbb.addInt64(6, object.timestamp);
        fbb.addOffset(7, formatOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final originalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final outputPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final outputFileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final originalBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final compressedBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final formatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = CompressionHistoryModel(
          id: idParam,
          originalPath: originalPathParam,
          outputPath: outputPathParam,
          outputFileName: outputFileNameParam,
          originalBytes: originalBytesParam,
          compressedBytes: compressedBytesParam,
          timestamp: timestampParam,
          format: formatParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CompressionHistoryModel] entity fields to define ObjectBox queries.
class CompressionHistoryModel_ {
  /// See [CompressionHistoryModel.id].
  static final id = obx.QueryIntegerProperty<CompressionHistoryModel>(
    _entities[0].properties[0],
  );

  /// See [CompressionHistoryModel.originalPath].
  static final originalPath = obx.QueryStringProperty<CompressionHistoryModel>(
    _entities[0].properties[1],
  );

  /// See [CompressionHistoryModel.outputPath].
  static final outputPath = obx.QueryStringProperty<CompressionHistoryModel>(
    _entities[0].properties[2],
  );

  /// See [CompressionHistoryModel.outputFileName].
  static final outputFileName =
      obx.QueryStringProperty<CompressionHistoryModel>(
        _entities[0].properties[3],
      );

  /// See [CompressionHistoryModel.originalBytes].
  static final originalBytes =
      obx.QueryIntegerProperty<CompressionHistoryModel>(
        _entities[0].properties[4],
      );

  /// See [CompressionHistoryModel.compressedBytes].
  static final compressedBytes =
      obx.QueryIntegerProperty<CompressionHistoryModel>(
        _entities[0].properties[5],
      );

  /// See [CompressionHistoryModel.timestamp].
  static final timestamp = obx.QueryIntegerProperty<CompressionHistoryModel>(
    _entities[0].properties[6],
  );

  /// See [CompressionHistoryModel.format].
  static final format = obx.QueryStringProperty<CompressionHistoryModel>(
    _entities[0].properties[7],
  );
}
